title: Neroal遊戲開發日常
author: Neroal
email: b0543019@ems.niu.edu.tw
description: 主要使用Unity和Unreal平台開發遊戲，會使用的語言有c#、c++、java、python，偶爾會上傳一些教學，希望能給予同在遊戲設計這條不歸路的同伴一些幫助
 
show_excerpts: true # set to true to show excerpts on the homepage
baseurl: "/"

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
sass:
  sass_dir: _sass

permalink: /posts/:title/
texture:
  title: Neroal
  tagline: Developer.
  date_format: "%b %-d, %Y"
  style: black
  showNav: true
  showPicker: true

  # generate social links in footer
  social_links:   
    facebook: neroal
    github: neroal
    linkedIn: 
    rss: rss
 

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up

#header_pages:
# - about.md

# Build settings
# theme: texture

plugins:
  - jekyll-seo-tag
#  - jekyll-feed